name       : latte-dock
version    : 0.10.1
release    : 34
source     :
    - https://cdn.download.kde.org/stable/latte-dock/latte-dock-0.10.1.tar.xz : 63f59a6d5ca91c31a115d24c907b3e90761199bb7e948c4123da85f9b0e38d0d
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Dock based on plasma frameworks
description: |
    Latte is a dock based on plasma frameworks that provides an elegant and intuitive experience for your tasks and plasmoids. It animates its contents by using parabolic zoom effect and trys to be there only when it is needed.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(xcb-event)
    - kactivities-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kio-devel
    - kirigami2-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kwayland-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
