name       : latte-dock
version    : 0.8.6
release    : 10
source     :
    - https://cdn.download.kde.org/stable/latte-dock/latte-dock-0.8.6.tar.xz : 63b95ee939ce0819935fe198e3c4e4cd7f98943f959a9b98dd68afe9a64beee3
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Dock based on plasma frameworks
description: |
    Latte is a dock based on plasma frameworks that provides an elegant and intuitive experience for your tasks and plasmoids. It animates its contents by using parabolic zoom effect and trys to be there only when it is needed.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(xcb-event)
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
