name       : latte-dock
version    : 0.9.12
release    : 33
source     :
    - https://cdn.download.kde.org/stable/latte-dock/latte-dock-0.9.12.tar.xz : b2b8af8c69eb122ccbbe987b00fff4d9d3ac9ccc939cbddae9fd319bca0630be
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Dock based on plasma frameworks
description: |
    Latte is a dock based on plasma frameworks that provides an elegant and intuitive experience for your tasks and plasmoids. It animates its contents by using parabolic zoom effect and trys to be there only when it is needed.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(xcb-event)
    - kactivities-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kwayland-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
