name       : latte-dock
version    : 0.10.7
release    : 39
source     :
    - https://download.kde.org/stable/latte-dock/latte-dock-0.10.7.tar.xz : de7a64328efd8dbb46d5129837aff6ca50429688627e7b0e9b9c45ad2ede63c4
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Dock based on plasma frameworks
description: |
    Latte is a dock based on plasma frameworks that provides an elegant and intuitive experience for your tasks and plasmoids. It animates its contents by using parabolic zoom effect and trys to be there only when it is needed.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(xcb-event)
    - kactivities-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kio-devel
    - kirigami2-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kwayland-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
