name       : latte-dock
version    : 0.7.5
release    : 3
source     :
    - https://cdn.download.kde.org/stable/latte-dock/latte-dock-0.7.5.tar.xz : 96a3cb1b2cccc744950a08596c9b10f513183129387baa6934303a49ebdcea41
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Dock based on plasma frameworks
description: |
    Latte is a dock based on plasma frameworks that provides an elegant and intuitive experience for your tasks and plasmoids. It animates its contents by using parabolic zoom effect and trys to be there only when it is needed.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(xcb-event)
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-framework-devel
setup      : |
    mkdir build; pushd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    cd $installdir; qml_cache
