name       : latte-dock
version    : 0.9.7
release    : 23
source     :
    - https://cdn.download.kde.org/stable/latte-dock/latte-dock-0.9.7.tar.xz : 980c11968de633f73c4067396bee5d3c722735d0a80290ba54dd906eb2f91ead
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Dock based on plasma frameworks
description: |
    Latte is a dock based on plasma frameworks that provides an elegant and intuitive experience for your tasks and plasmoids. It animates its contents by using parabolic zoom effect and trys to be there only when it is needed.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(xcb-event)
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - knewstuff-devel
    - knotifications-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libksysguard-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
